kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: "0.63.2"
    config: config.yaml

- name: publish
  image: lucap/drone-netlify
  settings:
    path: ./public
    site_id:
      from_secret: netlify_site_id
    token:
      from_secret: netlify_token
  when:
    event:
    - push

trigger:
  event:
  - push
  - pull_request
